// todos
export const GET_TODO_DATA = 'GET_TODO_DATA';
export const GET_TODO_DATA_LOADING = 'GET_TODO_DATA_LOADING'
export const UPDATE_TODO_DATA = 'UPDATE_TODO_DATA'
export const UPDATE_TODO_DATA_LOADING = 'UPDATE_TODO_DATA_LOADING'